# This file was generated by GoReleaser. DO NOT EDIT.
cask "golint-sl" do
  version "0.1.12"

  on_macos do
    on_arm do
      sha256 "bbf473e62a7b863114d17e36dec93b64fbb3d9eeb2aceb16b9b9a05c6198f281"
      url "https://github.com/spechtlabs/golint-sl/releases/download/v#{version}/golint-sl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c37f15c9d9e71850539d9da4f0ff6518515a0e4bbd0df52a8fd2a70b653b5cce"
      url "https://github.com/spechtlabs/golint-sl/releases/download/v#{version}/golint-sl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3f288fed08f2071573fec8648c78d19bd8b949122cef4430d8f336241e9620c0"
      url "https://github.com/spechtlabs/golint-sl/releases/download/v#{version}/golint-sl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b8d0982cec2dae952896d45563dd1e59a12a047b6f3def9a57e698c099b2f55a"
      url "https://github.com/spechtlabs/golint-sl/releases/download/v#{version}/golint-sl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "golint-sl"
  desc "SpechtLabs Go linter collection for production code patterns."
  homepage "https://golint.specht-labs.de"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "golint-sl"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/golint-sl"]
    end
  end

  # No zap stanza required
end
