# This file was generated by GoReleaser. DO NOT EDIT.
cask "kush" do
  version "1.2.1"

  on_macos do
    on_arm do
      sha256 "b1bbb773505b3452411fc4c8203389fc73bdf7d52b1d1c6ac87fb6e92d1ac907"
      url "https://github.com/spechtlabs/kush/releases/download/v#{version}/kush_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "189568b73eeeacd9e3220205c7526446175de32798ae411aae8fe900cc917602"
      url "https://github.com/spechtlabs/kush/releases/download/v#{version}/kush_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "dcbde91187c9fd6cb76486f232741832b1f395bef8cc42abb09ec21d8f19cecc"
      url "https://github.com/spechtlabs/kush/releases/download/v#{version}/kush_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1e663989cb7b9e25764c91f2cb0914a00d77aa6fb7df4f6d7e528507192a5cf7"
      url "https://github.com/spechtlabs/kush/releases/download/v#{version}/kush_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kush"
  desc "Ephemeral, isolated kube-context subshells: a private, throwaway kubeconfig per shell."
  homepage "https://kush.specht-labs.de"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kush"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kush"]
    end
  end

  # No zap stanza required
end
