# This file was generated by GoReleaser. DO NOT EDIT.
cask "kush" do
  version "1.2.2"

  on_macos do
    on_arm do
      sha256 "2fe812a2812b677aa5759af536c3d23021e18b5c0fb2dd4f7ab20eb5376d1c93"
      url "https://github.com/spechtlabs/kush/releases/download/v#{version}/kush_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "050d8db27a88decf720a3aacdb0e031e663270dbd899e9fc568715674eed0dc5"
      url "https://github.com/spechtlabs/kush/releases/download/v#{version}/kush_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4a9488b41a757fce35dfc7cc49cb2bf0eac98bd6032262030b4054d8492d35cc"
      url "https://github.com/spechtlabs/kush/releases/download/v#{version}/kush_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "42c268e639e407909278180277ecce5f10bf40702bab17cb00a2b2175174c4da"
      url "https://github.com/spechtlabs/kush/releases/download/v#{version}/kush_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kush"
  desc "Isolated kube-context subshells, each with its own throwaway kubeconfig"
  homepage "https://kush.specht-labs.de/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kush"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kush"]
    end
  end

  # No zap stanza required
end
