# This file was generated by GoReleaser. DO NOT EDIT.
cask "kush" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "4593939fd8a658186ed1bbd0588f4559925b6454433f8ccb33875ed67bd2a778"
      url "https://github.com/spechtlabs/kush/releases/download/v#{version}/kush_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c4fd72146a17373d48f922cd813428707e09f0584bc5f7794332a3dcdbad015a"
      url "https://github.com/spechtlabs/kush/releases/download/v#{version}/kush_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "725e523c151faf8f7a3c0dc39a740cc684d67c8e3299b08f5ab4125a72531df8"
      url "https://github.com/spechtlabs/kush/releases/download/v#{version}/kush_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ddfbca6ac4da3fc738ad2ca4b6ce0dc1e90f2992b5695265d887b6d0436f16fb"
      url "https://github.com/spechtlabs/kush/releases/download/v#{version}/kush_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kush"
  desc "Ephemeral, isolated kube-context subshells: a private, throwaway kubeconfig per shell."
  homepage "https://kush.specht-labs.de"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kush"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kush"]
    end
  end

  # No zap stanza required

end
