# This file was generated by GoReleaser. DO NOT EDIT.
cask "sigil" do
  version "0.6.3"

  on_macos do
    on_arm do
      sha256 "7d2773cffaaafe8e1e42255ae73d38c12712a9dedb6b02644a3787c48c2c46c1"
      url "https://github.com/spechtlabs/sigil/releases/download/v#{version}/sigil_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fce86175bbf9ad69702bda40b3f430eddc76eea43173a64cf09c417c15112855"
      url "https://github.com/spechtlabs/sigil/releases/download/v#{version}/sigil_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "ec69e1ccd075bc3613e8e7ca66a0e848ede6831741b561dcba6f12d7ed41e4a6"
      url "https://github.com/spechtlabs/sigil/releases/download/v#{version}/sigil_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "73b545afd5c3f67c9c604b964a8431f60e9b7bb6435d6446349529ade0f97ad0"
      url "https://github.com/spechtlabs/sigil/releases/download/v#{version}/sigil_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sigil"
  desc "A small, statically typed policy language for Go hosts"
  homepage "https://github.com/SpechtLabs/sigil"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sigil"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sigil"]
    end
  end

  # No zap stanza required
end
