# This file was generated by GoReleaser. DO NOT EDIT.
cask "sigil" do
  version "0.7.1"

  on_macos do
    on_arm do
      sha256 "31254e5e2f291a9eee27b52e7cfab8070639f492e6913c69ec37870a5dc8de63"
      url "https://github.com/spechtlabs/sigil/releases/download/v#{version}/sigil_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "860ea3499665f838ab94ad61d770c4fc20202ea2ae7d2035043ea12c76bab912"
      url "https://github.com/spechtlabs/sigil/releases/download/v#{version}/sigil_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d19c91f3dde28be1cec08e4a0da50ac04767ed9893869226378b406938d3d707"
      url "https://github.com/spechtlabs/sigil/releases/download/v#{version}/sigil_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b68333d168c0834e27bac0b0e821868d9ca3cdceab5585382551b175a43b271c"
      url "https://github.com/spechtlabs/sigil/releases/download/v#{version}/sigil_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sigil"
  desc "A small, statically typed policy language for Go hosts"
  homepage "https://github.com/SpechtLabs/sigil"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sigil"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sigil"]
    end
  end

  # No zap stanza required
end
