# This file was generated by GoReleaser. DO NOT EDIT.
cask "sigil" do
  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "3209297f0f6b74fb2a623488d8899f0ef1aafefd58f88d4c788e5cc90bb7ddea"
      url "https://github.com/spechtlabs/sigil/releases/download/v#{version}/sigil_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "d4f6896dafdbb45162191b84e6e4ff44be2339b8a07943b39b61b0c3162f15ec"
      url "https://github.com/spechtlabs/sigil/releases/download/v#{version}/sigil_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "36c525234bc74c8378bf544f7274e65f0857d55f282eeb99c1adf935ef32395e"
      url "https://github.com/spechtlabs/sigil/releases/download/v#{version}/sigil_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2ce385955f70c826588f700bfce34b325577a9d501c4536c6e0cf7f3c5150f24"
      url "https://github.com/spechtlabs/sigil/releases/download/v#{version}/sigil_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sigil"
  desc "A small, statically typed policy language for Go hosts"
  homepage "https://github.com/SpechtLabs/sigil"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sigil"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sigil"]
    end
  end

  # No zap stanza required
end
