# This file was generated by GoReleaser. DO NOT EDIT.
cask "tka" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "61a3d7e5c26e40c377879b80274d29cddb8556d2653253f5143778b0dc2a2a60"
      url "https://github.com/spechtlabs/tka/releases/download/v#{version}/tka_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "aae6fee798d9d8e2a494e56cd91992011819ad8adcf54c13fa2cd0e779f00d6d"
      url "https://github.com/spechtlabs/tka/releases/download/v#{version}/tka_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3ddbbcb133c0d3adf75f078dec8fb133cbbdb11ceb73b1e6c4dd0597b3de8307"
      url "https://github.com/spechtlabs/tka/releases/download/v#{version}/tka_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "821a3a5548cbb7c1d715fa6889258c37787a9de929f9c0a02aeaf04cb3bb41e5"
      url "https://github.com/spechtlabs/tka/releases/download/v#{version}/tka_#{version}_linux_amd64.tar.gz"
    end
  end

  name "tka"
  desc "Tailnet-native Kubernetes access with short-lived kubeconfigs"
  homepage "https://tka.specht-labs.de/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tka"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tka"]
    end
  end

  # No zap stanza required
end
