# This file is generated by the telegram-tui release workflow. DO NOT EDIT.
class Tgt < Formula
  desc "Keyboard-driven Telegram client for the terminal"
  homepage "https://github.com/SpechtLabs/telegram-tui"
  version "0.1.4"
  license "MIT"

  # Ordered to satisfy brew style's FormulaAudit/ComponentsOrder: livecheck
  # comes before the on_<os> blocks.
  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SpechtLabs/telegram-tui/releases/download/v0.1.4/tgt-0.1.4-aarch64-apple-darwin.tar.gz"
      sha256 "9b498685de868594d3b0bed93e6b80cfc56758f713c07e3728c63c14c1e924bd"
    end
    if Hardware::CPU.intel?
      url "https://github.com/SpechtLabs/telegram-tui/releases/download/v0.1.4/tgt-0.1.4-x86_64-apple-darwin.tar.gz"
      sha256 "68540c4c4698255813e877c8fa9a618a48aab6ea8678d618bd46c983f75d19c6"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/SpechtLabs/telegram-tui/releases/download/v0.1.4/tgt-0.1.4-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "1112f1ae7f3efa2f29681928cc38cfdd5633d863ae59eca35f620b20d709a73c"
    end
    if Hardware::CPU.intel?
      url "https://github.com/SpechtLabs/telegram-tui/releases/download/v0.1.4/tgt-0.1.4-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "74829861d713cbf715ccfc45f7c237cb8c32807f10a8c5350ad4ae5c9c98f8f1"
    end
  end

  # The tarball is a relocatable bin/ + lib/ pair: tgt loads TDLib through a
  # runpath the loader expands relative to the executable itself
  # (`@executable_path/../lib` on macOS, `$ORIGIN/../lib` on Linux), so the two
  # directories have to stay siblings. Keeping them under libexec is what makes
  # that safe here — libexec is the one prefix directory Homebrew does not link
  # into HOMEBREW_PREFIX, so libtdjson (and the C++ runtime bundled beside it on
  # Linux) never lands in the shared lib/. Both dyld and glibc's ld.so resolve
  # the symlink to its real path before expanding the runpath, so the linked
  # bin/tgt still finds libexec/lib.
  def install
    libexec.install Dir["tgt/*"]
    bin.install_symlink libexec/"bin/tgt"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tgt --version")
  end
end
