# This file is generated by the telegram-tui release workflow. DO NOT EDIT.
class Tgt < Formula
  desc "Keyboard-driven Telegram client for the terminal"
  homepage "https://github.com/SpechtLabs/telegram-tui"
  version "0.2.1"
  license "MIT"

  # Ordered to satisfy brew style's FormulaAudit/ComponentsOrder: livecheck
  # comes before the on_<os> blocks.
  livecheck do
    skip "Auto-generated on release."
  end

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/SpechtLabs/telegram-tui/releases/download/v0.2.1/tgt-0.2.1-aarch64-apple-darwin.tar.gz"
      sha256 "d5f670bb344992eaf13d2abbba8544bf46e3dd862c4924abad21aeb457c3b424"
    end
    if Hardware::CPU.intel?
      url "https://github.com/SpechtLabs/telegram-tui/releases/download/v0.2.1/tgt-0.2.1-x86_64-apple-darwin.tar.gz"
      sha256 "f5d71fcb7054fc50c1729ee16924fa916f81c765b01406632b4a681c82ce7d3a"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/SpechtLabs/telegram-tui/releases/download/v0.2.1/tgt-0.2.1-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "0e7559253c9b62428d5262985eff9a381f61ba3ac563ac38418e56b27a989c52"
    end
    if Hardware::CPU.intel?
      url "https://github.com/SpechtLabs/telegram-tui/releases/download/v0.2.1/tgt-0.2.1-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "7f9d3b47fd50c1b10bea9c706cf6fbda10b5b3d61333319bf68fc14aad0d9fbe"
    end
  end

  # The tarball is a relocatable bin/ + lib/ pair: tgt loads TDLib through a
  # runpath the loader expands relative to the executable itself
  # (`@executable_path/../lib` on macOS, `$ORIGIN/../lib` on Linux), so the two
  # directories have to stay siblings. Keeping them under libexec is what makes
  # that safe here — libexec is the one prefix directory Homebrew does not link
  # into HOMEBREW_PREFIX, so libtdjson (and the C++ runtime bundled beside it on
  # Linux) never lands in the shared lib/. Both dyld and glibc's ld.so resolve
  # the symlink to its real path before expanding the runpath, so the linked
  # bin/tgt still finds libexec/lib.
  # Homebrew strips a single top-level directory when it stages an archive, so
  # by the time this runs the working directory already *is* the contents of
  # the tarball's tgt/ — globbing "tgt/*" matches nothing, and v0.1.4 installed
  # an empty libexec and a dangling bin symlink because of it. The dotfile glob
  # is separate because Ruby's Dir["*"] skips dotfiles, which would silently
  # drop the .tgt-install marker that `tgt update` reads to confirm a tree is
  # ours. Dir returns [] when it matches nothing, so this stays correct for
  # releases predating the marker.
  def install
    libexec.install Dir["*"] + Dir[".tgt-install"]
    bin.install_symlink libexec/"bin/tgt"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tgt --version")
  end
end
